name: main
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install And Package
        run: |
          docker run --rm -v "$PWD":/var/task lambci/lambda:build-nodejs12.x npm install --only=prod
          docker run --rm -v "$PWD":/var/task lambci/lambda:build-nodejs12.x zip -9yr lambda.zip .
      - name: Update And Publish
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
        run: |
          docker run --rm -v "$PWD/lambda.zip":/var/task/lambda.zip -e AWS_REGION=$AWS_REGION -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY lambci/lambda:build-nodejs12.x aws lambda update-function-code --function-name cdn_4sitive_com-origin_request --zip-file fileb://lambda.zip
          docker run --rm -v "$PWD/lambda.zip":/var/task/lambda.zip -e AWS_REGION=$AWS_REGION -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY lambci/lambda:build-nodejs12.x aws lambda publish-version --function-name cdn_4sitive_com-origin_request


